'use client';
import { AppLayout } from '@/components/app-layout';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Share2, DollarSign } from 'lucide-react';
import Link from 'next/link';

const EarningTable = () => {
    const earningsData = [];
    for (let i = 1; i <= 15; i++) {
      let commission = 0;
      if (i <= 5) {
        commission = 0.2;
      } else {
        commission = 0.1;
      }
      earningsData.push({ level: i, commission: `${commission}%` });
    }

    return (
        <Card>
            <CardHeader>
                <div className="flex items-center gap-4">
                    <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-green-500/10 text-green-500">
                        <DollarSign className="h-6 w-6" />
                    </div>
                    <div>
                        <CardTitle className="text-2xl font-headline">Earning Commission by Level</CardTitle>
                        <CardDescription>
                            Your affiliate program offers deep, multi-level rewards. You earn a percentage of the revenue generated by members in your network, down to 15 levels.
                        </CardDescription>
                    </div>
                </div>
            </CardHeader>
            <CardContent>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Level</TableHead>
                            <TableHead className="text-right">Commission Rate</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {earningsData.map((earning) => (
                            <TableRow key={earning.level}>
                                <TableCell>Level {earning.level}</TableCell>
                                <TableCell className="text-right font-medium">{earning.commission}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
                 <div className="p-4 rounded-lg border bg-green-500/10 text-green-700 mt-6">
                    <h4 className="font-semibold text-lg flex items-center gap-2">Total Commission: <span className="text-green-600">2% Distributed</span></h4>
                    <p className="text-muted-foreground mt-1 text-green-800">This structure allows you to benefit from the network effect, as your earnings grow exponentially with your team's expansion.</p>
                </div>
            </CardContent>
             <CardFooter>
                <Button asChild>
                    <Link href="/register">Start Building Your Team</Link>
                </Button>
            </CardFooter>
        </Card>
    );
  };

export default function AffiliatePage() {
  return (
    <AppLayout>
      <div className="flex flex-col gap-8">
        <EarningTable />
      </div>
    </AppLayout>
  );
}
