'use client';
import { AppLayout } from '@/components/app-layout';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Share2, Star } from 'lucide-react';

export default function InfluencerPage() {
  return (
    <AppLayout>
      <div className="flex flex-col gap-8">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-orange-500/10 text-orange-500">
                <Share2 className="h-6 w-6" />
              </div>
              <div>
                <CardTitle className="text-2xl font-headline">Influencer Earning Program</CardTitle>
                <CardDescription>Join our program and earn rewards for sharing our vision.</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-6">
            <div>
              <h3 className="font-semibold">The Mission</h3>
              <p className="text-muted-foreground">
                Help us share our vision with the world. 1% of revenue from the first 5 token stages is allocated to a prize pool for influencers. Rewards are distributed based on the total views your content generates on platforms like YouTube, Instagram, Facebook, and Twitter.
              </p>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <h4 className="font-semibold">How it Works</h4>
              <p className="mt-2 text-muted-foreground">
                The influencer prize pool from your country is divided by the total views generated by all participating influencers, creating a "per-view" reward rate. Your earnings are calculated based on your total verified views.
              </p>
            </div>
            <div className="rounded-lg border-2 border-amber-400 bg-amber-400/10 p-4">
              <h4 className="font-semibold flex items-center gap-2"><Star className="h-5 w-5 text-amber-500"/>Special Reward Announcement</h4>
              <p className="mt-2 text-muted-foreground">
                For **October, November, and December 2025**, a special reward is active! During these months, **2%** of the total funds raised from your country will be allocated to a dedicated influencer prize pool.
              </p>
              <p className="mt-2 text-muted-foreground">
                This special 2% pool will be distributed based on the total views your content generates within your country. More views mean a larger share of the prize! This reward is funded by a deduction from the Creator Fund to empower our growing community of influencers.
              </p>
            </div>
            <div className="rounded-lg border bg-card p-4">
              <h4 className="font-semibold">Apply to be an Influencer</h4>
              <p className="mt-2 text-muted-foreground">
                Fill out the form below to apply. Provide links to your main social media profiles.
              </p>
              <form className="mt-4 space-y-4">
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="influencer-name">Full Name</Label>
                    <Input id="influencer-name" placeholder="John Doe" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="influencer-email">Email Address</Label>
                    <Input id="influencer-email" type="email" placeholder="john.doe@example.com" />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="youtube-link">YouTube Channel Link</Label>
                  <Input id="youtube-link" placeholder="https://www.youtube.com/..." />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="twitter-link">Twitter/X Profile Link</Label>
                  <Input id="twitter-link" placeholder="https://twitter.com/..." />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="instagram-link">Instagram Profile Link</Label>
                  <Input id="instagram-link" placeholder="https://www.instagram.com/..." />
                </div>
              </form>
            </div>
          </CardContent>
          <CardFooter>
            <Button>Submit Application</Button>
          </CardFooter>
        </Card>
      </div>
    </AppLayout>
  );
}