
// This is the entry point for deploying your Genkit flows as Cloud Functions.
// This file is automatically generated by Firebase Studio. Do not modify it.

import { https } from 'firebase-functions';
import { onRequest } from 'firebase-functions/v2/https';

import * as distributeCommission from './distributeCommission';

// Expose the flows so that they can be called from the client.
export const distributeCommissionTrigger = distributeCommission.distributeCommission;

// This is a generic handler that can be used to trigger any flow.
// This is used for calling flows from the Firebase Studio UI.
export const handler = onRequest(
  async (req: https.Request, res: https.Response): Promise<void> => {
    const { flowId, input } = req.body.data;
    if (!flowId) {
      res.status(400).send({ error: 'flowId is required' });
      return;
    }
    // You can add more flows here.
    const flows: Record<string, (input: any) => Promise<any>> = {};

    const flow = flows[flowId];
    if (!flow) {
      res.status(404).send({ error: `Flow ${flowId} not found` });
      return;
    }
    try {
      const output = await flow(input);
      res.status(200).send({ output });
    } catch (e: any) {
      console.error(e);
      res.status(500).send({ error: e.message });
    }
  }
);
